### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by Laura7089** [FragSoc/tmodloader-docker#1]
The container throws an (unhelpful) error on start.

We know the attached dockerfile + docker-compose worked.

**Comment by Laura7089** [comment]
```Dockerfile
FROM debian:stretch-slim AS downloader

ARG SERVER_REMOTE="https://terraria.org/system/dedicated_servers/archives/000/000/042/original/terraria-server-1412.zip"
ARG TMODLOADER_REMOTE="https://github.com/tModLoader/tModLoader/releases/download/v0.11.8.1/tModLoader.Linux.v0.11.8.1.zip"

RUN apt-get update && \
    apt-get install -y unzip curl

RUN curl -L -o /tmp/terrariaServer.zip ${SERVER_REMOTE} && \
    curl -L -o /tmp/tModLoader.zip ${TMODLOADER_REMOTE} && \
    unzip -d /tmp /tmp/terrariaServer.zip && \
    unzip -d /tmp/tModLoader /tmp/tModLoader.zip

FROM debian:stretch-slim AS runner

ARG SERVER_VER_INT="1412"
ARG UID="999"

ENV INSTALL_LOC="/terraria"
ENV WORLDS_LOC="/worlds"
ENV MODS_LOC="/mods"
ENV LOGS_LOC="/logs"

ENV TERRARIA_DATA="/root/.local/share/Terraria/ModLoader"

# TODO: fix; readd chowns to COPYs, adjust TERRARIA_DATA etc
# RUN useradd -m -u ${UID} -s /bin/false terraria

COPY --from=downloader /tmp/${SERVER_VER_INT}/Linux ${INSTALL_LOC}
COPY --from=downloader /tmp/tModLoader/* ${INSTALL_LOC}/

RUN chmod +x ${INSTALL_LOC}/tModLoaderServer* && \
    mkdir -p ${TERRARIA_DATA} && \
    ln -s ${WORLDS_LOC} ${TERRARIA_DATA}/Worlds && \
    ln -s ${MODS_LOC} ${TERRARIA_DATA}/Mods && \
    ln -s ${LOGS_LOC} ${TERRARIA_DATA}/Logs
    # chown -R terraria:terraria ${TERRARIA_DATA}

VOLUME ${WORLDS_LOC} ${MODS_LOC} ${LOGS_LOC}
WORKDIR ${INSTALL_LOC}
EXPOSE 7777
# USER terraria
ENTRYPOINT ["./tModLoaderServer.bin.x86_64"]
```

**Comment by Laura7089** [comment]
```yaml
version: "3"

services:
  terraria:
    build: .
    command: -config /config.txt
    image: fragsoc/tmodloader
    stdin_open: true
    tty: true
    volumes:
      - "./worlds:/worlds"
      - "./mods:/mods"
      - "./config.txt:/config.txt"
    ports:
      - "7777:7777"
```
